<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\DepthVideo.Core\DepthVideo.Core.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <BaseOutputPath>..\..\artifacts\build\</BaseOutputPath>
  </PropertyGroup>

  <ItemGroup>
    <Content Include="..\..\models\depth_anything_v2_small_fp16.onnx" Link="models\depth_anything_v2_small_fp16.onnx">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="..\..\models\depth_anything_v2_small_q8.onnx" Link="models\depth_anything_v2_small_q8.onnx">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

</Project>
